# Workaround for https://status.dev.azure.com/_event/179641421
trigger:
  branches:
    include:
    - '*'
pr:
  branches:
    include:
    - '*'

schedules:
# 8am UTC is midnight PST.
- cron: '0 8 * * *'
  displayName: Daily midnight build
  branches:
    include:
    - '*'

variables:
  system.debug: true

jobs:

- job: canary_jobs
  dependsOn:
   - junit_jdk21
   - nonjunit_jdk21
   - inference_part1_jdk21
   - inference_part2_jdk21
   - typecheck_part1_jdk21
   - typecheck_part2_jdk21
   - misc_jdk21
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - bash: true
    displayName: canary_jobs

- job: junit_jdk21
  pool:
    vmImage: 'ubuntu-latest'
  container: mdernst/cf-ubuntu-jdk21:latest
  timeoutInMinutes: 70
  steps:
  - checkout: self
    fetchDepth: 25
  - bash: ./checker/bin-devel/test-cftests-junit.sh
    displayName: test-cftests-junit.sh
- job: nonjunit_jdk21
  pool:
    vmImage: 'ubuntu-latest'
  container: mdernst/cf-ubuntu-jdk21:latest
  steps:
  - checkout: self
    fetchDepth: 25
  - bash: ./checker/bin-devel/test-cftests-nonjunit.sh
    displayName: test-cftests-nonjunit.sh
# Split into part1 and part2 only for the inference job that "canary_jobs" depends on.
- job: inference_part1_jdk21
  pool:
    vmImage: 'ubuntu-latest'
  container: mdernst/cf-ubuntu-jdk21:latest
  timeoutInMinutes: 90
  steps:
  - checkout: self
    fetchDepth: 25
  - bash: ./checker/bin-devel/test-cftests-inference-part1.sh
    displayName: test-cftests-inference-part1.sh
- job: inference_part2_jdk21
  pool:
    vmImage: 'ubuntu-latest'
  container: mdernst/cf-ubuntu-jdk21:latest
  timeoutInMinutes: 90
  steps:
  - checkout: self
    fetchDepth: 25
  - bash: ./checker/bin-devel/test-cftests-inference-part2.sh
    displayName: test-cftests-inference-part2.sh
- job: misc_jdk21
  pool:
    vmImage: 'ubuntu-latest'
  container: mdernst/cf-ubuntu-jdk21-plus:latest
  steps:
  - checkout: self
  - bash: ./checker/bin-devel/test-misc.sh
    displayName: test-misc.sh
# This is a canary job, so it has no `dependsOn`.
# Split into part1 and part2 only for the type-checking job that "canary_jobs" depends on.
- job: typecheck_part1_jdk21
  pool:
    vmImage: 'ubuntu-latest'
  container: mdernst/cf-ubuntu-jdk21-plus:latest
  steps:
  - checkout: self
    fetchDepth: 1000
  - bash: ./checker/bin-devel/test-typecheck-part1.sh
    displayName: test-typecheck-part1.sh
- job: typecheck_part2_jdk21
  pool:
    vmImage: 'ubuntu-latest'
  container: mdernst/cf-ubuntu-jdk21-plus:latest
  steps:
  - checkout: self
    fetchDepth: 1000
  - bash: ./checker/bin-devel/test-typecheck-part2.sh
    displayName: test-typecheck-part2.sh
- job: daikon_part1_jdk21
  dependsOn:
   - canary_jobs
  pool:
    vmImage: 'ubuntu-latest'
  container: mdernst/cf-ubuntu-jdk21:latest
  timeoutInMinutes: 70
  steps:
  - checkout: self
    fetchDepth: 25
  - bash: ./checker/bin-devel/test-daikon-part1.sh
    displayName: test-daikon.sh
- job: daikon_part2_jdk21
  dependsOn:
   - canary_jobs
  pool:
    vmImage: 'ubuntu-latest'
  container: mdernst/cf-ubuntu-jdk21:latest
  timeoutInMinutes: 80
  steps:
  - checkout: self
    fetchDepth: 25
  - bash: ./checker/bin-devel/test-daikon.sh
    displayName: test-daikon-part2.sh
- job: guava_jdk21
  dependsOn:
   - canary_jobs
  pool:
    vmImage: 'ubuntu-latest'
  container: mdernst/cf-ubuntu-jdk21:latest
  # The guava job sometimes times out, because the time between these lines can be 30 minutes!
  #   [INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugin-tools/maven-plugin-tools-generators/3.5.1/maven-plugin-tools-generators-3.5.1.pom
  #   [INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugin-tools/maven-plugin-tools-generators/3.5.1/maven-plugin-tools-generators-3.5.1.pom
  # I tried to configure Maven to prevent that problem, but it is still ocurring.
  # Maybe I need to use caching? https://learn.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops
  timeoutInMinutes: 70
  steps:
  - checkout: self
    fetchDepth: 25
  - bash: ./checker/bin-devel/test-guava.sh
    displayName: test-guava.sh
- job: plume_lib_jdk21
  dependsOn:
   - canary_jobs
  pool:
    vmImage: 'ubuntu-latest'
  container: mdernst/cf-ubuntu-jdk21:latest
  steps:
  - checkout: self
    fetchDepth: 25
  - bash: ./checker/bin-devel/test-plume-lib.sh
    displayName: test-plume-lib.sh

# TODO: add dependsOn.
- job: wpi_njr_part1_jdk17
  pool:
    vmImage: 'ubuntu-latest'
  container: mdernst/cf-ubuntu-jdk17:latest
  timeoutInMinutes: 150
  steps:
  - checkout: self
    fetchDepth: 25
  - bash: ./checker/bin-devel/test-njr.sh part1
    displayName: test-njr part1
- job: wpi_njr_part2_jdk17
  pool:
    vmImage: 'ubuntu-latest'
  container: mdernst/cf-ubuntu-jdk17:latest
  timeoutInMinutes: 150
  steps:
  - checkout: self
    fetchDepth: 25
  - bash: ./checker/bin-devel/test-njr.sh part2
    displayName: test-njr part2
- job: wpi_njr_part3_jdk17
  pool:
    vmImage: 'ubuntu-latest'
  container: mdernst/cf-ubuntu-jdk17:latest
  timeoutInMinutes: 150
  steps:
  - checkout: self
    fetchDepth: 25
  - bash: ./checker/bin-devel/test-njr.sh part3
    displayName: test-njr part3
- job: wpi_njr_part4_jdk17
  pool:
    vmImage: 'ubuntu-latest'
  container: mdernst/cf-ubuntu-jdk17:latest
  timeoutInMinutes: 150
  steps:
  - checkout: self
    fetchDepth: 25
  - bash: ./checker/bin-devel/test-njr.sh part4
    displayName: test-njr part4
- job: wpi_njr_part5_jdk17
  pool:
    vmImage: 'ubuntu-latest'
  container: mdernst/cf-ubuntu-jdk17:latest
  timeoutInMinutes: 150
  steps:
  - checkout: self
    fetchDepth: 25
  - bash: ./checker/bin-devel/test-njr.sh part5
    displayName: test-njr part5
- job: wpi_njr_part6_jdk17
  pool:
    vmImage: 'ubuntu-latest'
  container: mdernst/cf-ubuntu-jdk17:latest
  timeoutInMinutes: 150
  steps:
  - checkout: self
    fetchDepth: 25
  - bash: ./checker/bin-devel/test-njr.sh part6
    displayName: test-njr part6
- job: wpi_njr_part7_jdk17
  pool:
    vmImage: 'ubuntu-latest'
  container: mdernst/cf-ubuntu-jdk17:latest
  timeoutInMinutes: 150
  steps:
  - checkout: self
    fetchDepth: 25
  - bash: ./checker/bin-devel/test-njr.sh part7
    displayName: test-njr part7
- job: wpi_njr_part8_jdk17
  pool:
    vmImage: 'ubuntu-latest'
  container: mdernst/cf-ubuntu-jdk17:latest
  timeoutInMinutes: 150
  steps:
  - checkout: self
    fetchDepth: 25
  - bash: ./checker/bin-devel/test-njr.sh part8
    displayName: test-njr part8
